TRUNCATE TABLE "DW".country_mapping;

INSERT INTO "DW".country_mapping (country_es, country_en)
SELECT DISTINCT order_country, order_country 
FROM staging.raw_supply_chain_data;

UPDATE "DW".country_mapping
SET country_en = CASE 
    WHEN country_es LIKE 'Afganist%' THEN 'Afghanistan'
    WHEN country_es = 'Albania' THEN 'Albania'
    WHEN country_es = 'Alemania' THEN 'Germany'
    WHEN country_es = 'Angola' THEN 'Angola'
    WHEN country_es LIKE 'Arabia Saud%' THEN 'Saudi Arabia'
    WHEN country_es = 'Argelia' THEN 'Algeria'
    WHEN country_es = 'Argentina' THEN 'Argentina'
    WHEN country_es = 'Armenia' THEN 'Armenia'
    WHEN country_es = 'Australia' THEN 'Australia'
    WHEN country_es = 'Austria' THEN 'Austria'
    WHEN country_es LIKE 'Azerbaiy%' THEN 'Azerbaijan'
    WHEN country_es LIKE 'Banglad%' THEN 'Bangladesh'
    WHEN country_es = 'Barbados' THEN 'Barbados'
    WHEN country_es LIKE 'Bar%in' THEN 'Bahrain'
    WHEN country_es = 'Belice' THEN 'Belize'
    WHEN country_es LIKE 'Ben%n' THEN 'Benin'
    WHEN country_es = 'Bielorrusia' THEN 'Belarus'
    WHEN country_es LIKE 'B%lgica' THEN 'Belgium'
    WHEN country_es = 'Bolivia' THEN 'Bolivia'
    WHEN country_es = 'Bosnia y Herzegovina' THEN 'Bosnia and Herzegovina'
    WHEN country_es = 'Botsuana' THEN 'Botswana'
    WHEN country_es = 'Brasil' THEN 'Brazil'
    WHEN country_es = 'Bulgaria' THEN 'Bulgaria'
    WHEN country_es = 'Burkina Faso' THEN 'Burkina Faso'
    WHEN country_es = 'Burundi' THEN 'Burundi'
    WHEN country_es LIKE 'But%n' THEN 'Bhutan'
    WHEN country_es = 'Camboya' THEN 'Cambodia'
    WHEN country_es LIKE 'Camer%n' THEN 'Cameroon'
    WHEN country_es = 'Canada' THEN 'Canada'
    WHEN country_es = 'Chad' THEN 'Chad'
    WHEN country_es = 'Chile' THEN 'Chile'
    WHEN country_es = 'China' THEN 'China'
    WHEN country_es = 'Chipre' THEN 'Cyprus'
    WHEN country_es = 'Colombia' THEN 'Colombia'
    WHEN country_es = 'Corea del Sur' THEN 'South Korea'
    WHEN country_es = 'Costa de Marfil' THEN 'Ivory Coast'
    WHEN country_es = 'Costa Rica' THEN 'Costa Rica'
    WHEN country_es = 'Croacia' THEN 'Croatia'
    WHEN country_es = 'Cuba' THEN 'Cuba'
    WHEN country_es = 'Dinamarca' THEN 'Denmark'
    WHEN country_es = 'Ecuador' THEN 'Ecuador'
    WHEN country_es = 'Egipto' THEN 'Egypt'
    WHEN country_es = 'El Salvador' THEN 'El Salvador'
    WHEN country_es LIKE 'Emiratos %rabes Unidos' THEN 'United Arab Emirates'
    WHEN country_es = 'Eritrea' THEN 'Eritrea'
    WHEN country_es = 'Eslovaquia' THEN 'Slovakia'
    WHEN country_es = 'Eslovenia' THEN 'Slovenia'
    WHEN country_es LIKE 'Espa%a' THEN 'Spain'
    WHEN country_es = 'Estados Unidos' THEN 'United States'
    WHEN country_es = 'Estonia' THEN 'Estonia'
    WHEN country_es LIKE 'Etiop%a' THEN 'Ethiopia'
    WHEN country_es = 'Filipinas' THEN 'Philippines'
    WHEN country_es = 'Finlandia' THEN 'Finland'
    WHEN country_es = 'Francia' THEN 'France'
    WHEN country_es LIKE 'Gab%n' THEN 'Gabon'
    WHEN country_es = 'Georgia' THEN 'Georgia'
    WHEN country_es = 'Ghana' THEN 'Ghana'
    WHEN country_es = 'Grecia' THEN 'Greece'
    WHEN country_es = 'Guadalupe' THEN 'Guadeloupe'
    WHEN country_es = 'Guatemala' THEN 'Guatemala'
    WHEN country_es = 'Guayana Francesa' THEN 'French Guiana'
    WHEN country_es = 'Guinea' THEN 'Guinea'
    WHEN country_es = 'Guinea-Bissau' THEN 'Guinea-Bissau'
    WHEN country_es = 'Guinea Ecuatorial' THEN 'Equatorial Guinea'
    WHEN country_es = 'Guyana' THEN 'Guyana'
    WHEN country_es LIKE 'Hait%' THEN 'Haiti'
    WHEN country_es = 'Honduras' THEN 'Honduras'
    WHEN country_es = 'Hong Kong' THEN 'Hong Kong'
    WHEN country_es LIKE 'Hungr%a' THEN 'Hungary'
    WHEN country_es = 'India' THEN 'India'
    WHEN country_es = 'Indonesia' THEN 'Indonesia'
    WHEN country_es = 'Irak' THEN 'Iraq'
    WHEN country_es = 'Irlanda' THEN 'Ireland'
    WHEN country_es LIKE 'Ir%n' THEN 'Iran'
    WHEN country_es = 'Israel' THEN 'Israel'
    WHEN country_es = 'Italia' THEN 'Italy'
    WHEN country_es = 'Jamaica' THEN 'Jamaica'
    WHEN country_es LIKE 'Jap%n' THEN 'Japan'
    WHEN country_es = 'Jordania' THEN 'Jordan'
    WHEN country_es LIKE 'Kazajist%' THEN 'Kazakhstan'
    WHEN country_es = 'Kenia' THEN 'Kenya'
    WHEN country_es LIKE 'Kirguist%' THEN 'Kyrgyzstan'
    WHEN country_es = 'Kuwait' THEN 'Kuwait'
    WHEN country_es = 'Laos' THEN 'Laos'
    WHEN country_es LIKE 'L%bano' THEN 'Lebanon'
    WHEN country_es = 'Lesoto' THEN 'Lesotho'
    WHEN country_es = 'Liberia' THEN 'Liberia'
    WHEN country_es = 'Libia' THEN 'Libya'
    WHEN country_es = 'Lituania' THEN 'Lithuania'
    WHEN country_es = 'Luxemburgo' THEN 'Luxembourg'
    WHEN country_es = 'Macedonia' THEN 'North Macedonia'
    WHEN country_es = 'Madagascar' THEN 'Madagascar'
    WHEN country_es = 'Malasia' THEN 'Malaysia'
    WHEN country_es = 'Mali' THEN 'Mali'
    WHEN country_es = 'Marruecos' THEN 'Morocco'
    WHEN country_es = 'Martinica' THEN 'Martinique'
    WHEN country_es = 'Mauritania' THEN 'Mauritania'
    WHEN country_es = 'Moldavia' THEN 'Moldova'
    WHEN country_es = 'Mongolia' THEN 'Mongolia'
    WHEN country_es = 'Montenegro' THEN 'Montenegro'
    WHEN country_es = 'Mozambique' THEN 'Mozambique'
    WHEN country_es LIKE 'M%xico' THEN 'Mexico'
    WHEN country_es = 'Myanmar (Birmania)' THEN 'Myanmar'
    WHEN country_es = 'Namibia' THEN 'Namibia'
    WHEN country_es = 'Nepal' THEN 'Nepal'
    WHEN country_es LIKE 'N%ger' THEN 'Niger'
    WHEN country_es = 'Nicaragua' THEN 'Nicaragua'
    WHEN country_es = 'Nigeria' THEN 'Nigeria'
    WHEN country_es = 'Noruega' THEN 'Norway'
    WHEN country_es = 'Nueva Zelanda' THEN 'New Zealand'
    WHEN country_es LIKE 'Om%n' THEN 'Oman'
    WHEN country_es LIKE 'Pakist%' THEN 'Pakistan'
    WHEN country_es LIKE 'Panam%' THEN 'Panama'
    WHEN country_es LIKE 'Pap%a Nueva Guinea' THEN 'Papua New Guinea'
    WHEN country_es = 'Paraguay' THEN 'Paraguay'
    WHEN country_es LIKE 'Pa%ses Bajos' THEN 'Netherlands'
    WHEN country_es LIKE 'Per%' THEN 'Peru'
    WHEN country_es = 'Polonia' THEN 'Poland'
    WHEN country_es = 'Portugal' THEN 'Portugal'
    WHEN country_es = 'Qatar' THEN 'Qatar'
    WHEN country_es = 'Reino Unido' THEN 'United Kingdom'
    WHEN country_es LIKE 'Rep%blica Centroafricana' THEN 'Central African Republic'
    WHEN country_es LIKE 'Rep%blica Checa' THEN 'Czech Republic'
    WHEN country_es LIKE 'Rep%blica de Gambia' THEN 'Gambia'
    WHEN country_es LIKE 'Rep%blica del Congo' THEN 'Republic of the Congo'
    WHEN country_es LIKE 'Rep%blica Democr%tica del Congo' THEN 'Democratic Republic of the Congo'
    WHEN country_es LIKE 'Rep%blica Dominicana' THEN 'Dominican Republic'
    WHEN country_es = 'Ruanda' THEN 'Rwanda'
    WHEN country_es = 'Rumania' THEN 'Romania'
    WHEN country_es = 'Rusia' THEN 'Russia'
    WHEN country_es = 'Senegal' THEN 'Senegal'
    WHEN country_es = 'Serbia' THEN 'Serbia'
    WHEN country_es LIKE 'S%hara Occidental' THEN 'Western Sahara'
    WHEN country_es = 'Sierra Leona' THEN 'Sierra Leone'
    WHEN country_es = 'Singapur' THEN 'Singapore'
    WHEN country_es = 'Siria' THEN 'Syria'
    WHEN country_es = 'Somalia' THEN 'Somalia'
    WHEN country_es = 'Sri Lanka' THEN 'Sri Lanka'
    WHEN country_es = 'Suazilandia' THEN 'Eswatini'
    WHEN country_es LIKE 'SudAfrica' THEN 'South Africa'
    WHEN country_es LIKE 'Sud%n' THEN 'Sudan'
    WHEN country_es LIKE 'Sud%n del Sur' THEN 'South Sudan'
    WHEN country_es = 'Suecia' THEN 'Sweden'
    WHEN country_es = 'Suiza' THEN 'Switzerland'
    WHEN country_es = 'Surinam' THEN 'Suriname'
    WHEN country_es = 'Tailandia' THEN 'Thailand'
    WHEN country_es LIKE 'Taiw%n' THEN 'Taiwan'
    WHEN country_es = 'Tanzania' THEN 'Tanzania'
    WHEN country_es LIKE 'Tayikist%' THEN 'Tajikistan'
    WHEN country_es LIKE 'T%nez' THEN 'Tunisia'
    WHEN country_es = 'Togo' THEN 'Togo'
    WHEN country_es = 'Trinidad y Tobago' THEN 'Trinidad and Tobago'
    WHEN country_es LIKE 'Turkmenist%' THEN 'Turkmenistan'
    WHEN country_es LIKE 'Turqu%a' THEN 'Turkey'
    WHEN country_es = 'Ucrania' THEN 'Ukraine'
    WHEN country_es = 'Uganda' THEN 'Uganda'
    WHEN country_es = 'Uruguay' THEN 'Uruguay'
    WHEN country_es LIKE 'Uzbekist%' THEN 'Uzbekistan'
    WHEN country_es = 'Venezuela' THEN 'Venezuela'
    WHEN country_es = 'Vietnam' THEN 'Vietnam'
    WHEN country_es = 'Yemen' THEN 'Yemen'
    WHEN country_es = 'Yibuti' THEN 'Djibouti'
    WHEN country_es = 'Zambia' THEN 'Zambia'
    WHEN country_es = 'Zimbabue' THEN 'Zimbabwe'
    ELSE country_es 
END;