-- staging.sql
CREATE SCHEMA IF NOT EXISTS staging;

DROP TABLE IF EXISTS staging.raw_supply_chain_data;

CREATE TABLE staging.raw_supply_chain_data (
    type                            VARCHAR(50),
    days_for_shipping_real          VARCHAR(50),
    days_for_shipment_scheduled     VARCHAR(50),
    benefit_per_order               VARCHAR(50),
    sales_per_customer              VARCHAR(50),
    delivery_status                 VARCHAR(50),
    late_delivery_risk              VARCHAR(50),
    category_id                     VARCHAR(50),
    category_name                   VARCHAR(100),
    customer_city                   VARCHAR(100),
    customer_country                VARCHAR(100),
    customer_email                  VARCHAR(100),
    customer_fname                  VARCHAR(100),
    customer_id                     VARCHAR(50),
    customer_lname                  VARCHAR(100),
    customer_password               VARCHAR(100),
    customer_segment                VARCHAR(50),
    customer_state                  VARCHAR(50),
    customer_street                 VARCHAR(255),
    customer_zipcode                VARCHAR(50),
    department_id                   VARCHAR(50),
    department_name                 VARCHAR(100),
    latitude                        VARCHAR(50),
    longitude                       VARCHAR(50),
    market                          VARCHAR(50),
    order_city                      VARCHAR(100),
    order_country                   VARCHAR(100),
    order_customer_id               VARCHAR(50),
    order_date                      VARCHAR(50),
    order_id                        VARCHAR(50),
    order_item_cardprod_id          VARCHAR(50),
    order_item_discount             VARCHAR(50),
    order_item_discount_rate        VARCHAR(50),
    order_item_id                   VARCHAR(50),
    order_item_product_price        VARCHAR(50),
    order_item_profit_ratio         VARCHAR(50),
    order_item_quantity             VARCHAR(50),
    sales                           VARCHAR(50),
    order_item_total                VARCHAR(50),
    order_profit_per_order          VARCHAR(50),
    order_region                    VARCHAR(100),
    order_state                     VARCHAR(100),
    order_status                    VARCHAR(50),
    order_zipcode                   VARCHAR(50),
    product_card_id                 VARCHAR(50),
    product_category_id             VARCHAR(50),
    product_description             TEXT,
    product_image                   VARCHAR(255),
    product_name                    VARCHAR(255),
    product_price                   VARCHAR(50),
    product_status                  VARCHAR(50),
    shipping_date                   VARCHAR(50),
    shipping_mode                   VARCHAR(50)
);